### ISSUE TITLE
Network name not "fiware_default"

### ISSUE THREAD

**Issue by SBlechmann** [FIWARE/tutorials.IoT-over-MQTT#14]
Mine was named "tuttorialsiot-over-mqtt_default".
I'm not sure where to give the network a specific name.

**Comment by SBlechmann** [comment]
Well.... it only occured cause I started everything over 
"docker compose up -d".
For "./services start" it's named fiware_default.

**Comment by jason-fox** [comment]
If you start your **docker compose** using the `./service start` command as stated in the README, the network name is defined as **FIWARE** using the `-p` parameter [here]( https://github.com/FIWARE/tutorials.IoT-over-MQTT/blob/897a4c6e27d325cab9d5adeb3b7bbfcb6eadc151/services#L47)

```console
docker-compose --log-level ERROR -p fiware up -d --remove-orphans
```

**Comment by SBlechmann** [comment]
Yep, thanks :) got that a few seconds ago as well.

**Comment by SBlechmann** [comment]
I'm way too fast today, sorry.
Well, it's not stated in THIS README :) 
You could add that.

**Comment by jason-fox** [comment]
How to start the tutorial is stated in the [Start Up](https://github.com/FIWARE/tutorials.IoT-over-MQTT/blob/master/README.md#start-up) section.

> all services can be initialized from the command-line by running the services Bash script provided
> within the repository:
>
> `./services start`

I don't think further description of the docker-compose syntax is required ,since this isn't a docker-compose tutorial. The focus is purely on the IoT Agent Generic Enabler.

**Comment by SBlechmann** [comment]
Apparently, I've been always working on the websites (https://fiware-tutorials.readthedocs.io/en/latest/iot-over-mqtt/index.html etc.) and not directly from the readme files. 
Will do it from now on.

**Comment by jason-fox** [comment]
Fixed: Missing text added in ReadTheDocs: https://github.com/FIWARE/tutorials.Step-by-Step/commit/448fa75e360bc6bd4162a19085d8c95744e6ebbf
