### ISSUE TITLE
Lamp already exists

### ISSUE THREAD

**Issue by SBlechmann** [FIWARE/tutorials.IoT-over-MQTT#15]
When you want to provision the smart lamp in request 10 it already exists.

I deleted it manually and then provisioned it normally.

**Comment by jason-fox** [comment]
This is an issue with the ReadTheDocs documentation. The `README` has the correct request.

Fixed: https://github.com/FIWARE/tutorials.Step-by-Step/commit/5d3a98e59f836fdc939f2df9d0d4c400a60428fe

**Comment by SBlechmann** [comment]
Hi Jason,

thanks for your work!

I am still a bit confused:

You said it’s in issue with the ReadTheDocs. I now thought that ReadTheDocs is related to the webpages (https://fiware-tutorials.readthedocs.io/en/latest/iot-over-mqtt/index.html [1]). In [1] it was already correct while in the file you edited (https://github.com/FIWARE/tutorials.IoT-over-MQTT/tree/52b326d2b722ab765a83b19b820b5cdcad9765a7 [2]) it is still not correct. But maybe I’m just not getting the structure yet.

And I was actually talking about “10 request” in [1].

Thanks a lot and regards!
Sebastian

Von: Jason Fox <notifications@github.com>
Gesendet: Donnerstag, 18. Juli 2019 18:58
An: FIWARE/tutorials.IoT-over-MQTT <tutorials.IoT-over-MQTT@noreply.github.com>
Cc: Blechmann, Sebastian <sebastian.blechmann@eonerc.rwth-aachen.de>; Author <author@noreply.github.com>
Betreff: Re: [FIWARE/tutorials.IoT-over-MQTT] Lamp already exists (#15)


Closed #15<https://github.com/FIWARE/tutorials.IoT-over-MQTT/issues/15>.
