### ISSUE TITLE
How do I add seven levels in my topic

### ISSUE THREAD

**Issue by hacralo** [FIWARE/tutorials.IoT-over-MQTT#19]
I have a message broker deployed in my home which listens to multiple sensors at topic /xxxx/xxxx/xxxx/xxxx/xxxx/xxxx/xxxx. I am trying to connect the broker to iot-agent, but from fiware guide I can see the topic should be of format api-key/device-id/attrs. Is it possible to modify this topic structure to use my original seven level topic? I am new to this whole fiware setup, any help would be appreciated, thanks!

**Comment by jason-fox** [comment]
You won't be able to use a *Standard* IoT Agent for that, you will need to create your own custom IoT Agent.

The definition of the MQTT Topics to subscribe to can be found within [MQTTBinding.js](https://github.com/telefonicaid/iotagent-ul/blob/master/lib/bindings/MQTTBinding.js)

The reading of incoming messages can be found in [commonBindings.js](https://github.com/telefonicaid/iotagent-ul/blob/master/lib/commonBindings.js#L246)

To alter the  path you will need to follow the instructions found in [205 - Custom IoT Agent](https://github.com/FIWARE/tutorials.Custom-IoT-Agent)

- clone the [base repository](https://github.com/telefonicaid/iotagent-ul)
- branch from the **latest** release.
- Amend `MQTTBinding.js` and `commonBindings.js` to listen to your preferred  location
- Create your own [Dockerfile](https://github.com/FIWARE/tutorials.Custom-IoT-Agent/blob/master/iot-agent/Dockerfile) which uses the `COPY` instruction

Obviously same applies if using the JSON IoT Agent.

**Comment by hacralo** [comment]
that was helpful, thanks Jason!
