### ISSUE TITLE
DEVICE_GROUP_NOT_FOUND with MQTT measure

### ISSUE THREAD

**Issue by jason-fox** [FIWARE/tutorials.IoT-over-MQTT#8]
Related: https://github.com/telefonicaid/iotagent-ul/issues/320

For the Ultralight IoT agent, in the previous release **1.7** if an MQTT measure arrived , when the flow of the code looked for a service group resource was ignored. Therefore the tutorial (setting the resource to blank) was fine when run against **1.7.** The behaviour of the iot agent has changed for current release **1.8** and I can't see where the change has been documented, so maybe this is unexpected behaviour.

Either way it is fair to say that the current tutorial doesn't work with the current IoT Agent and one of them (or both) needs to be fixed.

**Comment by yuryskaletskiy** [comment]
Getting the issue too :(

**Comment by jason-fox** [comment]
As of v 1.11.0, the old functionality has been reacquired. Tutorial now working against latest versions of enablers
